CC = clang
CFLAGS = -Wall -Wextra -pedantic -std=c99

chpt2: ex1 ex3 ex4

ex1:
	$(CC) $(CFLAGS) -o ex1 Exercises/ex1.c

ex3:
	$(CC) $(CFLAGS) -o ex3 Exercises/ex3.c

ex4:
	$(CC) $(CFLAGS) -o ex4 Exercises/ex4.c

clean:
	rm ex1 ex3 ex4