CC = clang
CFLAGS = -Wall -Wextra -pedantic -std=c99

all: exercises projects

exercises: ex1 ex3 ex4

projects: proj1 proj2 proj3 proj4 proj5 proj6 proj7 proj8

# Exercises
ex1:
	$(CC) $(CFLAGS) -o ex1 Exercises/Ex1/ex1.c

ex3:
	$(CC) $(CFLAGS) -o ex3 Exercises/Ex3/ex3.c

ex4:
	$(CC) $(CFLAGS) -o ex4 Exercises/Ex4/ex4.c

# Projects
proj1:
	$(CC) $(CFLAGS) -o proj1 Projects/proj1.c

proj2:
	$(CC) $(CFLAGS) -o proj2 Projects/proj2.c

proj3:
	$(CC) $(CFLAGS) -o proj3 Projects/proj3.c

proj4:
	$(CC) $(CFLAGS) -o proj4 Projects/proj4.c

proj5:
	$(CC) $(CFLAGS) -o proj5 Projects/proj5.c

proj6:
	$(CC) $(CFLAGS) -o proj6 Projects/proj6.c

proj7:
	$(CC) $(CFLAGS) -o proj7 Projects/proj7.c

proj8:
	$(CC) $(CFLAGS) -o proj8 Projects/proj8.c

clean:
	rm ex1 ex3 ex4 proj1 proj2 proj3 proj4 proj5 proj6 proj7 proj8